site_name: Universidade de Ciência da Computação
site_url: https://NandesLima.github.io/ciencia-da-computacao/
site_description: Um currículo 100% gratuito e autodidata em Computer Science, do básico aos algoritmos avançados e IA, unificando trilhas universitárias e crash-courses (cursos livres).
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

extra_css:
  - stylesheets/custom.css
  - stylesheets/global-modern.css
extra_javascript:
  - javascripts/progress.js

nav:
  - 'Técnicas de estudo, organização e aprendizagem': 01-tecnicas-de-estudo-organizacao-e-aprendizagem.md
  - 'Git e GitHub': 02-git-e-github.md
  - 'Introdução à Computação': 03-introducao-à-computacao.md
  - 'Aprofundamento de Conceitos Introdutórios': 04-aprofundamento-de-conceitos-introdutorios.md
  - 'Desenvolvimento Técnico': 05-desenvolvimento-tecnico.md
  - 'Desenvolvimento Teórico': 06-desenvolvimento-teorico.md
  - 'Aprofundamento Técnico': 07-aprofundamento-tecnico.md
  - 'Tópicos Finais': 08-topicos-finais.md
  - 'Especializações': 09-especializacões.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - tables
